Loading in parse_game.py -> using his functions to convert pgn to hdf5 file format -> we may not want to use the same encoding or methodology, but the staple is her 

In [1]:
import numpy as np
import chess
import chess.pgn
from parse_game import *

In [10]:
filename = 'ficsgamesdb_201701_standard2000_nomovetimes_1452545.pgn'
oname = 'test.hdf5'

In [11]:
read_all_games(filename,oname)

80
resizing to 1
136
resizing to 3
32
resizing to 7
142
33
103
40
resizing to 15
29
41
104
80
139
64
106
129
resizing to 31
61
117
65
80
60
13
60
152
2 moves left
winner: -1
OrderedDict([('Event', 'FICS rated standard game'), ('Site', 'FICS freechess.org'), ('Date', '2017.01.30'), ('Round', '?'), ('White', 'wahyudi'), ('Black', 'hastrman'), ('Result', '1-0'), ('FICSGamesDBGameNo', '410957240'), ('WhiteElo', '2304'), ('BlackElo', '1903'), ('WhiteRD', '73.8'), ('BlackRD', '71.5'), ('BlackIsComp', 'Yes'), ('TimeControl', '900+0'), ('Time', '21:55:00'), ('WhiteClock', '0:15:00.000'), ('BlackClock', '0:15:00.000'), ('ECO', 'E92'), ('PlyCount', '151')])
. . . . . . . .
. . . . . . . .
. . . . . K . .
. . . . . . . p
. . . . . . . P
P . . R . . . .
. k . . Q . P .
. . . . . . . .
checkmate: True
71
53
171
75
164
176
51
168
1 moves left
winner: 1
OrderedDict([('Event', 'FICS rated standard game'), ('Site', 'FICS freechess.org'), ('Date', '2017.01.30'), ('Round', '?'), ('White', 'grandkhvtiso')

Below we have just some testing I did with the python-chess module

In [ ]:
ga = games[0]
b = ga.board()
ga.variations
gend = ga.end()
gend.board()
moves = []
for move in ga.main_line():
    moves.append(move)

    

In [ ]:
p = gend.board().pieces
idx = 0
for a, b in enumerate(p):
    idx = idx+1
    pass



In [5]:
file = open(filename)
games = []
t = chess.pgn.read_game(file)
while t:
    games.append(t)
    t = chess.pgn.read_game(file)

In [4]:
g = games[0]

In [6]:
game = parse_game(g)

80


In [9]:
game

(array([4, 0, 3, 4, 0, 0, 0, 0, 0, 0, 0, 0, 6, 1, 0, 0, 1, 0, 0, 0, 1, 0, 0,
        0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], dtype=int8),
 array([ 0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
         0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  8,
         0,  9,  0,  0,  0,  0, 15,  0,  0,  0, 22,  0,  0,  0,  0,  0,  0,
         0, 13, 29,  0,  0, 11,  0, 10, 18,  0,  0,  0,  0], dtype=int8),
 array([4, 0, 3, 4, 0, 0, 0, 0, 0, 0, 0, 0, 6, 1, 0, 0, 1, 0, 0, 0, 1, 0, 0,
        0, 0, 1, 0, 2, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], dtype=int8),
 26,
 -1)

In [ ]:
idx = 0
for ga in g:
    if (idx == 0):
        gout = ga
    idx = idx + 1

In [ ]:
gout